theme: jekyll-theme-cayman

title: Elegant
markdown: kramdown
highlighter: rouge
author:
  name:       Gaurav Panchal
  url:        https://elegantfrontend.training

url: "https://elegantfrontend.training"
baseurl: "/"
google_analytics: "G-R8YKPS191K"

plugins:
  - jekyll-sitemap